version: 2
defaults: &defaults
  working_directory: /go/src/github.com/segersniels/supdock
  docker:
    - image: circleci/golang

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "Install glide and generate vendor"
          command: |
            curl https://glide.sh/get | sh
            glide install
      - run:
          name: "Build testing binary"
          command: GOOS=linux go build -o bin/supdock
      - run:
          name: "Test if binary is executable"
          command: ./bin/supdock -h
      - run:
          name: "Release binary"
          command: ./gorelease.sh
